steps:
- name: 'sglahn/platformio-core:3.6.0'  
  dir: .
  args: ['run']  
artifacts: 
  objects: 
    location: 'gs://pooltemp_ato_firmware/$TAG_NAME'
    paths: ['/workspace/.pioenvs/d1/firmware_d1.bin']
